//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int Consulta_id { get; set; }
        public Nullable<System.DateTime> Data_Agendamento { get; set; }
        public Nullable<System.DateTime> Data_Hora { get; set; }
        public Nullable<bool> Is_Valida { get; set; }
        public int Cliente_comercio_id { get; set; }
        public string Cliente_comercio_Email { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public int Pets_pet_id { get; set; }
        public Nullable<bool> IsCancelada { get; set; }
        public string Quemcancelou { get; set; }
        public string Motivo { get; set; }
    
        public virtual Cliente_Comercio Cliente_Comercio { get; set; }
        public virtual Pets Pets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
