//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consulta()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int consulta_id { get; set; }
        public Nullable<System.DateTime> data_hora { get; set; }
        public Nullable<bool> is_valida { get; set; }
        public int cliente_comercio_id { get; set; }
        public string cliente_comercio_cnpj { get; set; }
        public Nullable<decimal> preco { get; set; }
        public int pets_pet_id { get; set; }
        public Nullable<bool> iscancelada { get; set; }
        public string quemcancelou { get; set; }
        public string motivo { get; set; }
    
        public virtual cliente_comercio cliente_comercio { get; set; }
        public virtual pets pets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
