//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int ID_Pagamento { get; set; }
        public string Numero_Cartao { get; set; }
        public string Proprietario_Cartao { get; set; }
        public Nullable<System.DateTime> Data_Validade { get; set; }
        public string CVC { get; set; }
        public int Usuario_id { get; set; }
        public string Usuario_Email { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
