//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet_fotos
    {
        public int id { get; set; }
        public string fotoCaminho { get; set; }
        public int pet_id { get; set; }
    
        public virtual pets pets { get; set; }
    }
}
