//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pets()
        {
            this.consulta = new HashSet<consulta>();
            this.Pet_fotos = new HashSet<Pet_fotos>();
        }
    
        public int pet_id { get; set; }
        public string nome { get; set; }
        public string what_pet { get; set; }
        public string breed { get; set; }
        public Nullable<decimal> wheight { get; set; }
        public string size { get; set; }
        public string description { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public int cliente_pessoa_id { get; set; }
        public string cliente_pessoa_cpf { get; set; }
    
        public virtual cliente_pessoa cliente_pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consulta> consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet_fotos> Pet_fotos { get; set; }
    }
}
