//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public int Cliente_Comercio_ID { get; set; }
        public string Cliente_Comercio_Email { get; set; }
        public int Consulta_Consulta_ID { get; set; }
    
        public virtual Cliente_Comercio Cliente_Comercio { get; set; }
        public virtual Consulta Consulta { get; set; }
    }
}
