//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public int Cliente_Comercio_ID { get; set; }
        public string Cliente_Comercio_CNPJ { get; set; }
        public int Consulta_Consulta_ID { get; set; }
    
        public virtual cliente_comercio cliente_comercio { get; set; }
        public virtual consulta consulta { get; set; }
    }
}
