//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Cliente_Comercio = new HashSet<Cliente_Comercio>();
            this.Cliente_Pessoa = new HashSet<Cliente_Pessoa>();
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Cpf_Cnpj { get; set; }
        public string Celular { get; set; }
        public Nullable<int> Idade { get; set; }
        public string Endereco { get; set; }
        public string Cep { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Data_cadastro { get; set; }
    
        public virtual Autenticacao Autenticacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Comercio> Cliente_Comercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Pessoa> Cliente_Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
