//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.cliente_comercio = new HashSet<cliente_comercio>();
            this.cliente_pessoa = new HashSet<cliente_pessoa>();
            this.payment = new HashSet<payment>();
        }
    
        public string nome { get; set; }
        public string email { get; set; }
        public int id { get; set; }
        public string cpf_cnpj { get; set; }
        public string cellphone { get; set; }
        public string telephone { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string cep { get; set; }
        public string reference { get; set; }
    
        public virtual Autenticacao Autenticacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_comercio> cliente_comercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_pessoa> cliente_pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payment { get; set; }
    }
}
