//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinarioServiceEntities : DbContext
    {
        public VeterinarioServiceEntities()
            : base("name=VeterinarioServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autenticacao> Autenticacao { get; set; }
        public virtual DbSet<Cliente_Comercio> Cliente_Comercio { get; set; }
        public virtual DbSet<Cliente_Pessoa> Cliente_Pessoa { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<Pet_fotos> Pet_fotos { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
