//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiVeterinario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinarioEntities : DbContext
    {
        public VeterinarioEntities()
            : base("name=VeterinarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autenticacao> Autenticacao { get; set; }
        public virtual DbSet<cliente_comercio> cliente_comercio { get; set; }
        public virtual DbSet<cliente_pessoa> cliente_pessoa { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<Pet_fotos> Pet_fotos { get; set; }
        public virtual DbSet<pets> pets { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
